### ISSUE TITLE
minor mistyping of PaymentRequestObject

### ISSUE THREAD

**Issue by riperk** [bitcoinjs/bolt11#20]
`PaymentRequestObject` is defined as having a:

https://github.com/bitcoinjs/bolt11/blob/5ce112c68ec9da90e127bf423a4bb8cff5037968/payreq.d.ts#L24-L25

which is not compatible with nulls:

https://github.com/bitcoinjs/bolt11/blob/5ce112c68ec9da90e127bf423a4bb8cff5037968/payreq.js#L779-L780

So either the type should be changed to `X | null` or should actually use `undefined` like the type declaration.

**Comment by junderw** [comment]
Thanks for the report!

**Comment by junderw** [comment]
Published as 1.2.6
