### ISSUE TITLE
private key used in example

### ISSUE THREAD

**Issue by tiero** [bitcoinjs/bolt11#25]
How the private key used in the README.md has been derived?

I'm trying to do with bitcoinJS 
```
bitcoin.ECPair.fromWIF("e126f68f7eafcc8b74f54d269fe206be715000f94dac067d1c04a8ca3b2db734", bitcoin.networks.testnet)
```

but I got `Error: Non-base58 character`

**Comment by mandelmonkey** [comment]
the private key is in hex not WIF format, I guess you need to do 
const privateKey = new Buffer('<PRIVATE KEY>', 'hex');
bitcoin.ECPair.fromPrivateKey(privateKey)
