### ISSUE TITLE
'satoshis' field not set for valid bolt11 -- but 'millisatoshis' is set

### ISSUE THREAD

**Issue by Sword-Smith** [bitcoinjs/bolt11#27]
My c-lightning implementation verifies that this is a valid bolt11 invoice. But the `satoshis` field is not set for this invoice. Is that because it is not a whole number of satoshis, s.t. we must use the `millisatoshis` field instead?

**Comment by junderw** [comment]
please post the invoice.

**Comment by Sword-Smith** [comment]
This is the invoice:
`lnbc9678785340p1pwmna7lpp5gc3xfm08u9qy06djf8dfflhugl6p7lgza6dsjxq454gxhj9t7a0sd8dgfkx7cmtwd68yetpd5s9xar0wfjn5gpc8qhrsdfq24f5ggrxdaezqsnvda3kkum5wfjkzmfqf3jkgem9wgsyuctwdus9xgrcyqcjcgpzgfskx6eqf9hzqnteypzxz7fzypfhg6trddjhygrcyqezcgpzfysywmm5ypxxjemgw3hxjmn8yptk7untd9hxwg3q2d6xjcmtv4ezq7pqxgsxzmnyyqcjqmt0wfjjq6t5v4khxxqyjw5qcqp2rzjq0gxwkzc8w6323m55m4jyxcjwmy7stt9hwkwe2qxmy8zpsgg7jcuwz87fcqqeuqqqyqqqqlgqqqqn3qq9qs4x9qlmd57lq7wwr23n3a6pkayy3jpfucyptlncs2maswe3dnnjy3ce2cgrvykmxlfpvn6ptqfqz4df5uaulvd4hjkckuqxrqqkz8jgphputwh`

And this is the output of Bolt11.decode(invoice):

coinType: "bitcoin"
complete: true
millisatoshis: "967878534"
payeeNodeKey: "02df5ffe895c778e10f7742a6c5b8a0cefbe9465df58b92fadeb883752c8107c8f"
paymentRequest: "lnbc9678785340p1pwmna7lpp5gc3xfm08u9qy06djf8dfflhugl6p7lgza6dsjxq454gxhj9t7a0sd8dgfkx7cmtwd68yetpd5s9xar0wfjn5gpc8qhrsdfq24f5ggrxdaezqsnvda3kkum5wfjkzmfqf3jkgem9wgsyuctwdus9xgrcyqcjcgpzgfskx6eqf9hzqnteypzxz7fzypfhg6trddjhygrcyqezcgpzfysywmm5ypxxjemgw3hxjmn8yptk7untd9hxwg3q2d6xjcmtv4ezq7pqxgsxzmnyyqcjqmt0wfjjq6t5v4khxxqyjw5qcqp2rzjq0gxwkzc8w6323m55m4jyxcjwmy7stt9hwkwe2qxmy8zpsgg7jcuwz87fcqqeuqqqyqqqqlgqqqqn3qq9qs4x9qlmd57lq7wwr23n3a6pkayy3jpfucyptlncs2maswe3dnnjy3ce2cgrvykmxlfpvn6ptqfqz4df5uaulvd4hjkckuqxrqqkz8jgphputwh"
prefix: "lnbc9678785340p"
recoveryFlag: 1
signature: "854c507f6da7be0f39c354671ee836e90919053cc102bfcf1056fb07662d9ce448e32ac206c25b66fa42c9e82b02402ab534e779f636b795b16e00c3002c23c9"
tags: (5) […]
timeExpireDate: 1573073503
timeExpireDateString: "2019-11-06T20:51:43.000Z"
timestamp: 1572468703
timestampString: "2019-10-30T20:51:43.000Z"
wordsTemp: "temp1pwmna7lpp5gc3xfm08u9qy06djf8dfflhugl6p7lgza6dsjxq454gxhj9t7a0sd8dgfkx7cmtwd68yetpd5s9xar0wfjn5gpc8qhrsdfq24f5ggrxdaezqsnvda3kkum5wfjkzmfqf3jkgem9wgsyuctwdus9xgrcyqcjcgpzgfskx6eqf9hzqnteypzxz7fzypfhg6trddjhygrcyqezcgpzfysywmm5ypxxjemgw3hxjmn8yptk7untd9hxwg3q2d6xjcmtv4ezq7pqxgsxzmnyyqcjqmt0wfjjq6t5v4khxxqyjw5qcqp2rzjq0gxwkzc8w6323m55m4jyxcjwmy7stt9hwkwe2qxmy8zpsgg7jcuwz87fcqqeuqqqyqqqqlgqqqqn3qq9qs4x9qlmd57lq7wwr23n3a6pkayy3jpfucyptlncs2maswe3dnnjy3ce2cgrvykmxlfpvn6ptqfqz4df5uaulvd4hjkckuqxrqqkz8jgpdzy7k8"

**Comment by junderw** [comment]
yes. if the amount is not a whole satoshi we only show millisatoshis.

decimals and JavaScript don't mix well.

**Comment by Sword-Smith** [comment]
That makes sens. It would be nice if the `"millisatoshis"` field was part of the documentation, though.

**Comment by Sword-Smith** [comment]
Closed by the merging of 4cc4c418c1e21abf19b5a8ec9a4094d4557cc1a7
