### ISSUE TITLE
Support Satoshis only [for now]

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bolt11#4]
On a discussion with @roasbeef,  the suggestion was that msats will be too confusing in the short term,  and 

> I don't really see msat being used for anything, at least in the short term

and 

> lnd always display sat, and accepts sat (on the rpc layer)

I propose,  until the use cases come out,  we temporarily drop the support and deal only in `satoshis`.

Thoughts @junderw ?

**Comment by junderw** [comment]
I agree. I have reverted to handling satoshis on wip branch

**Comment by jordodev** [comment]
I am using this great little library in a lightning wallet I'm developing but have noticed some merchants (eg. Blockstream store) are now encoding invoices in msats.

Could decoding support for millisatoshis be added?
Currently invoices with a 'p' divisor fail saying "Amount is outside of valid range"

**Comment by junderw** [comment]
@jordodev could you make a new issue please? Also provide any names of services already using mSats. Thanks.
