### ISSUE TITLE
Travis updates

### ISSUE THREAD

**Issue by junderw** [bitcoinjs/bolt11#5]
@dcousens I noticed the builds were failing for travis on Node 4 and 5.

Default node when installing apt on Ubuntu 16.04 is v6

Which is already getting pretty old.
What are your thoughts on removing v4 and v5 from the supported versions?

**Comment by dcousens** [comment]
https://github.com/nodejs/Release#release-schedule

I say we wait until the EOL? Then we can roll out across the entire organization?
April 2018.

**Comment by junderw** [comment]
Well, for now, until we ES5-ify bech32 and bolt11, those Travis tests will fail every time.

idk how Travis works for OSS, but it seems like a waste of processing time.

**Comment by dcousens** [comment]
@junderw 14 days to EOL for 4.0.0 (and 5.0.0).
Feel free to remove from .travis. 

It'd be good to get a PR ready for each repository under the organization and amend the `package.json` files throughout.

**Comment by junderw** [comment]
oh boy! haha.

I'll take some time later this week.

Here's a list of all the repos, please edit this message to remove any repos we won't need to update. (github.io comes to mind)

```
bech32
bip174
bip21
bip32
bip32-utils
bip32-wallet
bip38
bip39
bip44-constants
bip65
bip66
bip68
bip69
bitcoin-ops
bitcoinjs-lib
bitcoinjs-message
bitcoinjs.github.io
blkdat-stream
bolt11
bs58check
coinselect
indexd
merkle-lib
minimaldata
playground
private-bitcoin
pushdata-bitcoin
safe-transaction
tif
utxo
varuint-bitcoin
wif
```

**Comment by dcousens** [comment]
That's not including the crypto-browserify repos that we will need to do too lol.  But they are less pressing I suppose

**Comment by dcousens** [comment]
@calvinmetcalfe @fanatid how proactive do we want to be here?

**Comment by dcousens** [comment]
And cryptocoinjs

**Comment by junderw** [comment]
hmmmm................................

I could try to make a bash script that will generate tons of pull requests...

**Comment by dcousens** [comment]
@junderw can you make an issue for the "organization" batch update of travis to the main repo?

**Comment by junderw** [comment]
ok

**Comment by junderw** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1266

Made a central issue.
