### ISSUE TITLE
Update bitcoinjs-lib dependency to the latest version (from v3.3.1 to v6.0)

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bolt11#52]
Currently `bolt11` uses bitcoinjs-lib `v3.3.1`. This is a very old version.

The API used from `bitcoinjs-lib` is:
 - `toBase58Check()`
 - `fromBase58Check()`
 - `toBech32()`
 - `fromBech32()`

Please let me know if it is OK to:
- update to the latest `bitcoinjs-lib` version (6.0)
- bump the version of this lib to `1.3.3` (from 1.3.2)

If yes, then I will open a PR with the changes.

**Comment by junderw** [comment]
This can also allow fallback address to be segwit v1 as well, and remove the dependency on tiny-secp256k1.

Yes this would be a good change I think.
