### ISSUE TITLE
Is it possible to add custom tags to the invoice

### ISSUE THREAD

**Issue by PatrickGeyer** [bitcoinjs/bolt11#65]
Would like to encode an invoice and include the "h" tag

**Comment by PatrickGeyer** [comment]
Or is that an alias for the "purpose_commit_hash"? https://github.com/lightning/bolts/blob/master/11-payment-encoding.md

**Comment by junderw** [comment]
Yes.

purpose_commit_hash is for longer descriptions, and only includes the hash of the long message in the invoice.
