### ISSUE TITLE
Encoding with small timestamp values result in bad payment request

### ISSUE THREAD

**Issue by sangaman** [bitcoinjs/bolt11#68]
If I encode an invoice using a `payment_hash` tag and a small timestamp value such as `0` or `1`, either by manually setting it as a parameter on the `encode()` call or by mocking the time such that `new Date()` returns the epoch date, the encoded & signed payment request is corrupted without any of the expected tags or signature.

**Comment by junderw** [comment]
Pushed fix as v1.4.1

**Comment by sangaman** [comment]
> Pushed fix as v1.4.1

Can confirm that using this version fixed the issues I was seeing. Thank you!
