### ISSUE TITLE
npm package outdated

### ISSUE THREAD

**Issue by Tschaul** [bitcoinjs/bolt11#8]
Hi, i want to use you code to build a better version of https://lndecode.com/ . One that shows the payee node public key, so one can use it at yalls.org for example. Could you npm publish the current version so i can properly use it. Right now i just copied it over.

**Comment by junderw** [comment]
@dcousens I don't have publish rights for bolt11 on npm.

**Comment by dcousens** [comment]
@fanatid could you add @junderw to the [npm bitcoinjs org](https://www.npmjs.com/settings/bitcoin-js/members)?

**Comment by fanatid** [comment]
@junderw can you say you username on npmjs? Unfortunately I can add only to package, for adding to organization I think that we need @jprichardson

**Comment by junderw** [comment]
@fanatid 

https://www.npmjs.com/~junderw

**Comment by fanatid** [comment]
![screenshot from 2018-11-23 15-38-48](https://user-images.githubusercontent.com/2633065/48944017-18507a80-ef36-11e8-9d4a-3a25d3c955f9.png)
It's funny, @junderw probably I was able add you to organization, did you received any invitations?

**Comment by junderw** [comment]
@fanatid try `~junderw`

**Comment by fanatid** [comment]
It's not work too, I think it's not possible add anybody to one package, while this user is not in organization...

**Comment by junderw** [comment]
I just added and removed you from my package and `fanatid` was fine. I added you, then removed you three times it worked fine.

perhaps it is because the package is in an organization and only org members can be invited......?

**Comment by fanatid** [comment]
Yep, I talk exactly about this, because organization... I tried add you here:
![screenshot from 2018-11-23 15-50-20](https://user-images.githubusercontent.com/2633065/48944379-821d5400-ef37-11e8-8241-d0164152c407.png)
but your username just showed on second and then disappeared...

**Comment by junderw** [comment]
weird....... you can see my profile at this link, right? https://www.npmjs.com/~junderw

**Comment by fanatid** [comment]
Yes, I can see it. Only 1 package `bitcoin-js-benkyokai`.

**Comment by dcousens** [comment]
@jprichardson maybe add @fanatid as an owner?

**Comment by junderw** [comment]
@Tschaul I went ahead and pushed 1.1.0 to npm.
